import type { Metadata, Viewport } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/contexts/CartContext";
import { WishlistProvider } from "@/contexts/WishlistContext";

const poppins = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shynora Ecommerce",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "#f6ebc9",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="hydrated" suppressHydrationWarning>
      <head />
      <body className={`${poppins.className} antialiased`}>
        <CartProvider>
          <WishlistProvider>
            <div>{children}</div>
          </WishlistProvider>
        </CartProvider>
      </body>
    </html>
  );
}
